### ISSUE TITLE
[Help] 文件管理，上传文件失败！

### ISSUE THREAD

**Issue by zhengkang2020** [PKUHPC/SCOW#1020]
### 是否已有关于该错误的issue或讨论？ | Is there an existing issue / discussion for this?

- [X] 我已经搜索过已有的issues和讨论 | I have searched the existing issues / discussions

### 发生了什么 | What happened

上传文件报错，这个大小在哪里修改或配置？
![image](https://github.com/PKUHPC/SCOW/assets/67989011/b9abf320-c599-497a-be96-b841003b25f0)

```html
<html> <head><title>413 Request Entity Too Large</title></head> <body> <center><h1>413 Request Entity Too Large</h1></center> <hr><center>nginx/1.20.1</center> </body> </html> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page -->
```

### 期望结果 | What did you expect to happen

期望能正常上传。

### 之前运行正常吗？ | Did this work before?

正常

### 复现方法 | Steps To Reproduce

1、文件管理
2、上传大于5M、10M的文件
3、报错复现

### 运行环境 | Environment

```Markdown
- OS: RockyLinux 9.3
- Scheduler: slurm-23.02.6
- Docker: Docker version 24.0.7
- Docker-compose: Docker Compose version v2.21.0
- SCOW cli: 1.2.0
- SCOW: master
- Adapter: 1.4
```

### 备注 | Anything else?
install.yaml
```yaml
# 网关配置
gateway:
#   # 限制整个系统上传（请求）文件的大小。默认1G
#   # 可接受的格式为nginx的client_max_body_size可接受的值
  uploadFileSizeLimit: 1G

#   # 限制后端服务发出响应的超时时间，默认60s
#   # 可接受的格式为nginx的proxy_read_timeout可接受的值
  proxyReadTimeout: 600s
```
