### ISSUE TITLE
[Help] The username contains illegal characters.

### ISSUE THREAD

**Issue by zhengkang2020** [PKUHPC/SCOW#1054]
提交作业包括新建交互式应用提示” The username contains illegal characters.“
![image](https://github.com/PKUHPC/SCOW/assets/67989011/2a3ef260-f403-4e0c-b20b-d8c782d5b5da)

**Comment by liu-shaobo** [comment]
看提示是用户名称有非法字符串，你的登录名是什么？

**Comment by zhengkang2020** [comment]
登录名是名.姓，例如`san.zhang`，现在这个是测试环境，之前是正常使用的，自从更新`快捷入口`后出现这个问题。
下面是`portal-server`的日志
```json
scow-portal-server-1  | {"level":50,"time":"2024-01-08T07:59:04.460Z","pid":17,"hostname":"529c1023611a","req":"10","path":"/scow.portal.JobService/ListAccounts","err":{"type":"Error","message":"13 INTERNAL: The username contains illegal characters.","stack":"Error: 13 INTERNAL: The username contains illegal characters.\n    at callErrorFromStatus (/app/node_modules/.pnpm/@grpc+grpc-js@1.9.11/node_modules/@grpc/grpc-js/build/src/call.js:31:19)\n    at Object.onReceiveStatus (/app/node_modules/.pnpm/@grpc+grpc-js@1.9.11/node_modules/@grpc/grpc-js/build/src/client.js:192:76)\n    at Object.onReceiveStatus (/app/node_modules/.pnpm/@grpc+grpc-js@1.9.11/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)\n    at Object.onReceiveStatus (/app/node_modules/.pnpm/@grpc+grpc-js@1.9.11/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)\n    at /app/node_modules/.pnpm/@grpc+grpc-js@1.9.11/node_modules/@grpc/grpc-js/build/src/resolving-call.js:99:78\n    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)\nfor call at\n    at ServiceClientImpl.makeUnaryRequest (/app/node_modules/.pnpm/@grpc+grpc-js@1.9.11/node_modules/@grpc/grpc-js/build/src/client.js:160:32)\n    at ServiceClientImpl.listAccounts (/app/node_modules/.pnpm/@grpc+grpc-js@1.9.11/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)\n    at /app/node_modules/.pnpm/@ddadaal+tsgrpc-client@0.17.7_@grpc+grpc-js@1.9.11/node_modules/@ddadaal/tsgrpc-client/lib/unary.js:18:13\n    at new Promise (<anonymous>)\n    at asyncClientCall (/app/node_modules/.pnpm/@ddadaal+tsgrpc-client@0.17.7_@grpc+grpc-js@1.9.11/node_modules/@ddadaal/tsgrpc-client/lib/unary.js:15:12)\n    at Object.listAccounts (/app/apps/portal-server/build/services/job.js:49:69)\n    at augmentedImplementations.<computed> [as listAccounts] (/app/node_modules/.pnpm/@ddadaal+tsgrpc-server@0.19.5_@grpc+grpc-js@1.9.11/node_modules/@ddadaal/tsgrpc-server/lib/server.js:76:59)\n    at handleUnary (/app/node_modules/.pnpm/@grpc+grpc-js@1.9.11/node_modules/@grpc/grpc-js/build/src/server.js:852:17)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","code":13,"details":"The username contains illegal characters.","metadata":{"content-type":["application/grpc"],"grpc-status-details-bin":[{"type":"Buffer","data":[8,13,18,41,84,104,101,32,117,115,101,114,110,97,109,101,32,99,111,110,116,97,105,110,115,32,105,108,108,101,103,97,108,32,99,104,97,114,97,99,116,101,114,115,46,26,77,10,40,116,121,112,101,46,103,111,111,103,108,101,97,112,105,115,46,99,111,109,47,103,111,111,103,108,101,46,114,112,99,46,69,114,114,111,114,73,110,102,111,18,33,10,31,85,83,69,82,95,67,79,78,84,65,73,78,95,73,76,76,69,71,65,76,95,67,72,65,82,65,67,84,69,82,83]}]}},"msg":"Error occurred. Return the error."}

```

**Comment by zhengkang2020** [comment]
开发环境更新后也出现同样的问题。。麻烦尽快跟进下，谢谢。

**Comment by zhengkang2020** [comment]
浏览器F12中的报错
![image](https://github.com/PKUHPC/SCOW/assets/67989011/7b6d2b53-fa82-42d7-ab48-d39f166f5c43)
![image](https://github.com/PKUHPC/SCOW/assets/67989011/6c48556d-c2f4-4534-8d61-9e1706ecbc91)

**Comment by zhengkang2020** [comment]
账户管理中移除用户报错

![image](https://github.com/PKUHPC/SCOW/assets/67989011/1b913b14-73b3-4a88-a29a-83a0f1ac9d07)

`立即同步调度器账户和用户封锁状态`报错

![image](https://github.com/PKUHPC/SCOW/assets/67989011/5e3b6ad3-ec66-4c9d-a5d4-c599eb19ebca)

**Comment by zhengkang2020** [comment]
新建scow初始化时，提示`用户ID与模式不匹配/^[a-z][a-z0-9_]{2,19}$/` ，是必须小写字母开头，数字结束吗？以前没有这个限制，问题是否与这个有关系？
![image](https://github.com/PKUHPC/SCOW/assets/67989011/ffa4e13d-51fe-4157-940d-3103e85dc0dd)

**Comment by zhengkang2020** [comment]
@liu-shaobo 有什么进展吗？

**Comment by zhengkang2020** [comment]
根据测试情况，应该是最近更新后账户、用户的ID要符合`"^[a-z][a-z0-9_]{2,19}$"`标准，但是之前新建的账户、用户ID中有`.`、`-`的都会报错，这个问题有其他解决方法吗？

**Comment by zhengkang2020** [comment]
确定是与`config/mis.yaml`中的账户和用户创建需要匹配的正则表达式有关，但是修改表达式为`"^[a-z][a-z0-9_.-]{2,19}$"`时，用户和账户可以创建，但是任然会有以上不能提交作业的问题。
```yaml
# 创建账户时，账户名的规则。不设置就没有限制
accountNamePattern:
  # 正则表达式
  regex: "^[a-z][a-z0-9_]{2,19}$"

  # 出错时的消息，对应上面的正则表达式
  # 此文本支持国际化
  errorMessage: "要求输入长度为3-20位，由小写字母、数字、下划线组成，且以小写字母开头的字符串"

# 创建用户相关配置
createUser:

  # 是否允许用户从SCOW中创建用户
  enabled: true

  # SCOW中创建用户界面是使用内置的（builtin）或者使用外置页面（external）
  # 默认builtin
  type: builtin

  # 内置创建用户界面配置
  builtin:
    # 用户ID的格式，不设置就没有限制
    userIdPattern:
      # 正则表达式
      regex: "^[a-z][a-z0-9_]{2,19}$"

      # 出错时的消息
      # 此文本支持国际化
      errorMessage: "要求输入长度为3-20位，由小写字母、数字、下划线组成，且以小写字母开头的字符串"
```

是否必须要新建符合规则的用户与账户，将“包含非法字符”的用户、账户新建，重新添加？
