### ISSUE TITLE
[Help] 新部署集群pull不下来镜像

### ISSUE THREAD

**Issue by zhengkang2020** [PKUHPC/SCOW#1304]
### 发生了什么 | What happened

新部署的集群，`./cli compose pull`报错
```shell
[root@scow scow]# ./cli compose pull
INFO: Loaded plugins: []
WARN[0000] /scow/docker-compose-1718775889890.yml: `version` is obsolete
[+] Pulling 12/12
 ✔ portal-server Skipped - Image is already being pulled by mis-web                                                                                                                  0.0s
 ✔ mis-server Skipped - Image is already being pulled by mis-web                                                                                                                     0.0s
 ✔ audit-db Skipped - Image is already being pulled by db                                                                                                                            0.0s
 ✔ gateway Skipped - Image is already being pulled by mis-web                                                                                                                        0.0s
 ✔ audit-server Skipped - Image is already being pulled by mis-web                                                                                                                   0.0s
 ✔ auth Skipped - Image is already being pulled by mis-web                                                                                                                           0.0s
 ✔ portal-web Skipped - Image is already being pulled by mis-web                                                                                                                     0.0s
 ✘ log Error                                                        context canceled                                                                                                 0.4s
 ✘ db Error                                                         context canceled                                                                                                 0.4s
 ✘ redis Error                                                      context canceled                                                                                                 0.4s
 ✘ mis-web Error                                                    pull access denied for mirrors.pku.edu.cn/pkuhpc-icode/scow, repository does not exist or may ...                0.4s
 ✘ novnc Error                                                      context canceled                                                                                                 0.4s
Error response from daemon: pull access denied for mirrors.pku.edu.cn/pkuhpc-icode/scow, repository does not exist or may require 'docker login': denied: <html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx/1.14.1</center>
</body>
</html>
```

下面是`install.yaml`
```yaml
[root@scow scow]# ./cli view-install
portal:
  basePath: /
  novncClientImage: ghcr.io/pkuhpc/novnc-client-docker:master
mis:
  basePath: /mis
  dbPassword: myst!chang3this
  mysqlImage: mysql:8
audit:
  dbPassword: must!chang3this
  mysqlImage: mysql:8
log:
  fluentd:
    image: fluentd:v1.14.0-1.0
    logDir: /var/log/fluentd
  level: info
  pretty: false
port: 80
basePath: /
image: mirrors.pku.edu.cn/pkuhpc-icode/scow
imageTag: master
gateway:
  protocol: http
  uploadFileSizeLimit: 1G
  proxyReadTimeout: 60s
  extra: ''
  allowedServerName: _
auth:
  redisImage: redis:alpine
plugins:
  pluginsDir: ./plugins


```

### 运行环境 | Environment

```Markdown
- OS: Rocky Linux 9.4 (Blue Onyx)
- Scheduler: slurm-23.11.1
- Docker: Docker version 26.1.4
- Docker-compose: Docker Compose version v2.26.1
- SCOW cli: Version 1.5.2
- SCOW: 1.5.2
- Adapter: 1.5.0
```

### 其他问题：
现在是否只有企业版有支持？githab issue好像不怎么活跃？
