### ISSUE TITLE
网关服务一直重启

### ISSUE THREAD

**Issue by wangqiangbj** [PKUHPC/SCOW#656]
gateway网关服务总是在重启，我试了v0.4.0以及master最新的镜像也不行。
![image](https://github.com/PKUHPC/SCOW/assets/25796741/57a34176-093c-4ac4-bd20-2a936e868b2a)

日志报错：
@scow/gateway:  { tag: 'v0.4.0', commit: 'd368fa621544235c64ba8914b0276bac7c165022' }
nginx: [emerg] duplicate location "/" in /etc/nginx/http.d/default.conf:24

感觉跟install.yaml中的basePath有关，因为我修改成/demo1报错就是duplicate location "/demo1" in /etc/nginx/http.d/default.conf:24

**Comment by ddadaal** [comment]
请给一下`install.yml`的配置

**Comment by daiqizhi** [comment]
可否展示一个最小化的可工作的install.yml?

**Comment by ddadaal** [comment]
install.yaml直接写一个空对象`{}`即可运行，但是这种情况下门户和管理系统都不会部署。

以下是一个测试集群正在使用的install.yml，请参考

```yaml
port: 80
basePath: /
image: ghcr.io/pkuhpc/scow/scow
imageTag: master
portal:
  portMappings: {}
mis:
  dbPassword: must!chang3this
  portMappings: {}
log:
  fluentd:
    logDir: /var/log/fluentd
```

在这个配置下，门户系统位于`/`，管理系统位于`/mis`
