### ISSUE TITLE
socw 管理系统 ssh 方式认证问题

### ISSUE THREAD

**Issue by ctao2022** [PKUHPC/SCOW#887]
使用node 16.14.0 版本，分别在docker中部署scow，使用的ssh认证方式，门户系统可以认证登录。输入用户名密码登录管理系统，或通过门户系统中的管理系统链接自动跳转到登录页面http://**/mis/api/auth/callback?token=xxx，都会重新跳转到登录界面。
直接访问http://***/mis/dashboard,会提示“您未登录或者登录状态已经过期。您需要登录才能访问此页面”。但能直接跳转到门户系统。
认证接口：mis/api/auth/validateToken？token=xxx 能获取信息，但管理系统的界面无法获取userInfo 信息，导致系统无法认证。

没有找到问题，望指点

**Comment by safeAndSound3** [comment]
我之前也遇到了这个问题 可以试下 scow/install.yaml  的image项目 tag改为v1.0.0

**Comment by ctao2022** [comment]
我用的不是默认镜像，是使用的发布后的代码，自己构建的镜像，mis、portal。

> 我之前也遇到了这个问题 可以试下 scow/install.yaml 的image项目 tag改为v1.0.0

**Comment by huangjun0210** [comment]
试试这个install.yaml

```
port: 80
basePath: /
imageTag: v1.0.0
portal:
  portMappings: {}
mis:
  dbPassword: must!chang3this
  portMappings: {}
log:
  fluentd:
    logDir: /var/log/fluentd
auth:
  portMappings: {}
audit:
  dbPassword: "must!chang3this"
gateway:
  proxyReadTimeout: 36000s
```
