### ISSUE TITLE
SCOW管理系统启动报错

### ISSUE THREAD

**Issue by zhengkang2020** [PKUHPC/SCOW#908]
## 查看状态
```shell
[root@scow scow]# ./cli compose ps
INFO: Loaded plugins: []
NAME                   IMAGE                                         COMMAND                                          SERVICE         CREATED              STATUS
scow-audit-db-1        mysql:8                                       "docker-entrypoint.sh mysqld"                    audit-db        About a minute ago   Up About a minute
scow-audit-server-1    mirrors.pku.edu.cn/pkuhpc-icode/scow:master   "./entrypoint.sh"                                audit-server    About a minute ago   Up About a minute              00/tcp
scow-auth-1            mirrors.pku.edu.cn/pkuhpc-icode/scow:master   "./entrypoint.sh"                                auth            About a minute ago   Up About a minute              00/tcp
scow-db-1              mysql:8                                       "docker-entrypoint.sh mysqld"                    db              About a minute ago   Up About a minute
scow-gateway-1         mirrors.pku.edu.cn/pkuhpc-icode/scow:master   "./entrypoint.sh"                                gateway         About a minute ago   Up About a minute              ->80/tcp, :::80->80/tcp, 5000/tcp
scow-mis-server-1      mirrors.pku.edu.cn/pkuhpc-icode/scow:master   "./entrypoint.sh"                                mis-server      About a minute ago   Restarting (1) 16 seconds ago
scow-mis-web-1         mirrors.pku.edu.cn/pkuhpc-icode/scow:master   "./entrypoint.sh"                                mis-web         About a minute ago   Up About a minute              00/tcp
scow-novnc-1           ghcr.io/pkuhpc/novnc-client-docker:master     "/docker-entrypoint.sh nginx -g 'daemon off;'"   novnc           About a minute ago   Up About a minute
scow-portal-server-1   mirrors.pku.edu.cn/pkuhpc-icode/scow:master   "./entrypoint.sh"                                portal-server   About a minute ago   Up About a minute              00/tcp
scow-portal-web-1      mirrors.pku.edu.cn/pkuhpc-icode/scow:master   "./entrypoint.sh"                                portal-web      About a minute ago   Up About a minute              00/tcp
scow-redis-1           redis:alpine                                  "docker-entrypoint.sh redis-server"              redis           About a minute ago   Up About a minute

```

## 报错日志
```shell
scow-mis-server-1  | > @scow/mis-server@1.0.0 serve
scow-mis-server-1  | > node build/index.js
scow-mis-server-1  |
scow-mis-server-1  | {"level":30,"time":1698114801619,"pid":18,"hostname":"cfe346c9cfcd","msg":"Hook disabled"}
scow-mis-server-1  | {"level":30,"time":1698114803246,"pid":18,"hostname":"cfe346c9cfcd","version":{"commit":"914f6c85f87302610dc2bc9b78706fa8b892d0eb"},"msg":"@scow/mis-server: "}
scow-mis-server-1  | {"level":30,"time":1698114803246,"pid":18,"hostname":"cfe346c9cfcd","config":{"HOST":"0.0.0.0","PORT":5000,"LOG_LEVEL":"info","LOG_PRETTY":false,"SSH_PRIVATE_KEY_PATH":"/root/.ssh/id_rsa","SSH_PUBLIC_KEY_PATH":"/root/.ssh/id_rsa.pub","DB_PASSWORD":"myst!chang3this"},"msg":"Loaded env config"}
scow-mis-server-1  | /app/node_modules/.pnpm/mysql2@3.5.2/node_modules/mysql2/lib/packets/packet.js:728
scow-mis-server-1  |     const err = new Error(message);
scow-mis-server-1  |                 ^
scow-mis-server-1  |
scow-mis-server-1  | Error: Access denied for user 'root'@'172.23.0.12' (using password: YES)
scow-mis-server-1  |     at Packet.asError (/app/node_modules/.pnpm/mysql2@3.5.2/node_modules/mysql2/lib/packets/packet.js:728:17)
scow-mis-server-1  |     at ClientHandshake.execute (/app/node_modules/.pnpm/mysql2@3.5.2/node_modules/mysql2/lib/commands/command.js:29:26)
scow-mis-server-1  |     at Connection.handlePacket (/app/node_modules/.pnpm/mysql2@3.5.2/node_modules/mysql2/lib/connection.js:478:34)
scow-mis-server-1  |     at PacketParser.onPacket (/app/node_modules/.pnpm/mysql2@3.5.2/node_modules/mysql2/lib/connection.js:97:12)
scow-mis-server-1  |     at PacketParser.executeStart (/app/node_modules/.pnpm/mysql2@3.5.2/node_modules/mysql2/lib/packet_parser.js:75:16)
scow-mis-server-1  |     at Socket.<anonymous> (/app/node_modules/.pnpm/mysql2@3.5.2/node_modules/mysql2/lib/connection.js:104:25)
scow-mis-server-1  |     at Socket.emit (node:events:517:28)
scow-mis-server-1  |     at addChunk (node:internal/streams/readable:335:12)
scow-mis-server-1  |     at readableAddChunk (node:internal/streams/readable:308:9)
scow-mis-server-1  |     at Readable.push (node:internal/streams/readable:245:10) {
scow-mis-server-1  |   code: 'ER_ACCESS_DENIED_ERROR',
scow-mis-server-1  |   errno: 1045,
scow-mis-server-1  |   sqlState: '28000',
scow-mis-server-1  |   sqlMessage: "Access denied for user 'root'@'172.23.0.12' (using password: YES)",
scow-mis-server-1  |   sql: undefined
scow-mis-server-1  | }
scow-mis-server-1  |
scow-mis-server-1  | Node.js v18.18.1
```

install.yaml
```yaml
... ...
mis:
#   # 门户系统路径相对于整个系统的部署路径。默认/
#   # 若设置则/开头，不要以/结尾.
#   # 如果BASE_PATH为/root1，PORTAL.BASE_PATH为/root2，那么最终访问管理系统的路径是/root1/root2
  basePath: /mis

#   # mysql数据库的镜像地址。默认为mysql:8
#   # mysqlImage: "mysql:8"

#   # 管理系统数据库的密码。如果部署管理系统，则必须配置
#   # 第一次启动管理系统时会使用此密码初始化管理系统数据库，之后如需修改需要手动在数据库中修改
  dbPassword: myst!chang3this

.... ...
```

mis.yaml
```yaml
# 管理系统数据库的信息。
# 如果直接使用scow-deployment提供的数据库，此部分内容不修改
db:
  host: db
  port: 3306
  user: root
  dbName: scow

# 获取作业相关配置
fetchJobs:
  # 周期性获取数据
  periodicFetch:
    # 是否开启
    enabled: true
    # 周期的cron表达式
    cron: "10 */10 * * * *"

# 预定义的充值类型
predefinedChargingTypes:
  - 测试
... ...
```

麻烦看下可能是什么问题？
