### ISSUE TITLE
创建GNOME类型的桌面，输入密码卡住

### ISSUE THREAD

**Issue by zhengkang2020** [PKUHPC/SCOW#940]
login节点的系统是RockyLinux9.2，第一次创建GNOME桌面正常进入，之后再“启动”输入密码卡住。
![image](https://github.com/PKUHPC/SCOW/assets/67989011/cd7c3fec-e7f2-47e5-91bd-490fa78069cf)
这个是TurboVNC 的限制问题吗？

**Comment by huangjun0210** [comment]
你的wm值用的是什么？

**Comment by zhengkang2020** [comment]
```yaml
# 是否启用作业管理功能
jobManagement: true

# 登录节点桌面功能
loginDesktop:
  # 是否启用桌面功能
  enabled: true

  # 桌面
  wms:
    # 桌面名和对应的wm值。见文档
    - name: Xfce
      wm: xfce
    - name: GNOME
      wm: 2d


  # 最多启动多少个桌面节点
  maxDesktops: 3

# 是否启用交互式任务功能
apps: true

......
```
